### ISSUE TITLE
img 路径 md5 问题

### ISSUE THREAD

**Issue by stephenzhao** [lcxfs1991/html-res-webpack-plugin#12]
想要html里面的img资源也支持md5怎么办呢？ 现在${require('./img/logo.png')}

**Comment by lcxfs1991** [comment]
能贴一下代码在这里吗？

**Comment by stephenzhao** [comment]
ok，简单的说吧，我现在遇到了多个生成html文件的问题，目前来说解决图片路径只有加上${require('./img/logo.png')} 才可以img-loader解析到编译的asset里面。
from
```html
<img src="${require('./img/pic.jpg')}" alt="">
```
build to 
```html
<img src="http://admin.corp.dajia365.com/img/pic.4738a5.jpg" alt="">
```
请问有别的解决办法嘛？

**Comment by lcxfs1991** [comment]
你是用react写吗？

**Comment by stephenzhao** [comment]
我用的vue

**Comment by stephenzhao** [comment]
用react就没这个问题了是吗？

**Comment by lcxfs1991** [comment]
我是用react的。。好像都是webpack帮忙处理的吧，html里的md5也会帮忙处理好。
vue没用过，vue是有点像angular的写法？东西都写在html里？

**Comment by lcxfs1991** [comment]
可加我qq249806703

**Comment by stephenzhao** [comment]
嗯东西都写在 html里了。

**Comment by lcxfs1991** [comment]
@stephenzhao 
终于花时间加上了。
