### ISSUE TITLE
使用多个html文件

### ISSUE THREAD

**Issue by PepperYan** [lcxfs1991/html-res-webpack-plugin#13]
使用多个html文件的时候,有不需要编写node代码,根据路径就能分别访问相应的html的方法吗?

**Comment by lcxfs1991** [comment]
你是说想好像以像gulp一样吗？

**Comment by xiaoweb** [comment]
我生成 多个html页面，但是有的页面不需要common.js 等模块，我需要怎么用才能配合webpack智能区分（不是使用预列出哪些页面不需要common）。
