### ISSUE TITLE
依赖没法自动安装

### ISSUE THREAD

**Issue by zhangyihua** [lcxfs1991/html-res-webpack-plugin#14]
package.json：

```js
"dependencies": {},
"devDependencies": {
    "lodash": "^3.10.1",
    "bluebird": "^3.1.1",
    "html-minifier": "^1.1.1"
  },
```

**Comment by lcxfs1991** [comment]
无法安装？内网有防火墙？

**Comment by zhangyihua** [comment]
是这样的，我在自己的项目里依赖这个插件，我执行 `npm install` 的时候会自动下载这个插件，但是由于你的依赖放到 `devDependencies` 里，所以不会自动下载。

我还有一个问题，这个插件是对 [html-webpack-plugin](https://www.npmjs.com/package/html-webpack-plugin) 的拓展吗？还是根本没什么关系？

**Comment by lcxfs1991** [comment]
我来fix一下，晚上更新。
我有参考html-webpack-plugin哈。
两者并没有什么关系。
可以看文档（中英文都有写），Why do I write a new html plugin。

**Comment by zhangyihua** [comment]
了解了   谢谢你

**Comment by lcxfs1991** [comment]
fixed 并发布成0.0.7了。可以试试。
