### ISSUE TITLE
htmlContent.replace is not function

### ISSUE THREAD

**Issue by qazzhoubin** [lcxfs1991/html-res-webpack-plugin#21]
Unhandled rejection TypeError: htmlContent.replace is not a
function
    at HtmlResWebpackPlugin.apply.compiler.plugin.compiler.plugin.Promise.resolv
e.then.then.HtmlResWebpackPlugin.buildStatsHtmlMode.HtmlResWebpackPlugin.printCh
unkName.HtmlResWebpackPlugin.buildStats.HtmlResWebpackPlugin.checkResource.HtmlR
esWebpackPlugin.injectAssets.injectChunks.map [as injectAssets] (E:\git\erp\node
_modules\html-res-webpack-plugin\index.js:475:28)

**Comment by lcxfs1991** [comment]
有没有装html-loader?
