### ISSUE TITLE
想写个插件在生成js的最前面 插入一段js代码  js代码window.pad = pad  pad是传进来的

### ISSUE THREAD

**Issue by wood-liu92** [lcxfs1991/html-res-webpack-plugin#22]
应该怎么在什么时候插入呢？ 怎么获取到webpack编译的代码呢？

**Comment by lcxfs1991** [comment]
可以使用，或者参考这个项目：
https://github.com/lcxfs1991/banner-webpack-plugin
@lww555

**Comment by wood-liu92** [comment]
![15f57187-8993-416e-a0ab-20efd5e3369d](https://user-images.githubusercontent.com/19809260/27852577-4b122c44-6192-11e7-8660-4a944c7b7a80.png)

代码已经插入进去了 但是总是报 as2 is not a function 这是怎么回事呢

**Comment by lcxfs1991** [comment]
你有在代码里，调用 window.pad() ?

**Comment by wood-liu92** [comment]
![image](https://user-images.githubusercontent.com/19809260/27853728-7dfced70-6196-11e7-8b85-a3118127d57f.png)
我在代码里没有调用 window.pad() 。

**Comment by lcxfs1991** [comment]
你多加个分号呢？

**Comment by wood-liu92** [comment]
可以了，果然是分号的事。谢谢大神

**Comment by wood-liu92** [comment]
最近想写webpack插件 但是看compiler， compilation的源码 完全看不懂啊。需要哪些基础知识呢.
是看 他提供的Plugin API吗？

**Comment by lcxfs1991** [comment]
老早的时候写的，有一定参考价值
https://github.com/lcxfs1991/blog/issues/1
另外这里也有一些文章参考：
https://github.com/webpack-china/awesome-webpack-cn
